  

version: '2'

volumes:
  orderer.docsshare.com:
  peer0.bng.com:
  peer1.bng.com:
  peer0.hyd.com:
  peer1.hyd.com:
  peer0.chn.com:
  peer1.chn.com:
  cli:

networks:
  docs:

services:
  orderer.docsshare.com:
    container_name: orderer.docsshare.com
    extends:
      file: org-abstract.yaml
      service: orderer-abstract
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/docsshare.com/orderers/orderer.docsshare.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/docsshare.com/orderers/orderer.docsshare.com/tls:/var/hyperledger/orderer/tls
        - orderer.docsshare.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
    networks:
      - docs

  peer0.bng.com:
    container_name: peer0.bng.com
    extends:
      file: org-abstract.yaml
      service: peer-abstract
    networks:
      - docs

  peer1.bng.com:
    container_name: peer1.bng.com
    extends:
      file: org-abstract.yaml
      service: peer-abstract
    networks:
      - docs

  peer0.hyd.com:
    container_name: peer0.hyd.com
    extends:
      file: org-abstract.yaml
      service: peer-abstract
    networks:
      - docs

  peer1.hyd.com:
    container_name: peer1.hyd.com
    extends:
      file: org-abstract.yaml
      service: peer-abstract
    networks:
      - docs

  peer0.chn.com:
    container_name: peer0.chn.com
    extends:
      file: org-abstract.yaml
      service: peer-abstract
    networks:
      - docs

  peer1.chn.com:
    container_name: peer1.chn.com
    extends:
      file: org-abstract.yaml
      service: peer-abstract
    networks:
      - docs




  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.bng.com:7051
      - CORE_PEER_LOCALMSPID=bngMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/bng.com/peers/peer0.bng.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/bng.com/peers/peer0.bng.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/bng.com/peers/peer0.bng.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/bng.com/users/Admin@bng.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts

    depends_on:
      - orderer.docsshare.com
      - peer0.bng.com
      - peer1.bng.com
      - peer0.hyd.com
      - peer1.hyd.com
      - peer0.chn.com
      - peer1.chn.com

    networks:
      - docs
